---
# Source: chatcord-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chatcord-chatcord-chart
  labels:
    helm.sh/chart: chatcord-chart-0.1.0
    app.kubernetes.io/name: chatcord-chart
    app.kubernetes.io/instance: chatcord
    app.kubernetes.io/version: "1.1"
    app.kubernetes.io/managed-by: Helm
