---
# Source: chatcord-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatcord-chatcord-chart
  labels:
    helm.sh/chart: chatcord-chart-0.1.0
    app.kubernetes.io/name: chatcord-chart
    app.kubernetes.io/instance: chatcord
    app.kubernetes.io/version: "1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chatcord-chart
      app.kubernetes.io/instance: chatcord
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chatcord-chart
        app.kubernetes.io/instance: chatcord
    spec:
      serviceAccountName: chatcord-chatcord-chart
      securityContext:
        {}
      containers:
        - name: chatcord-chart
          securityContext:
            {}
          image: "salamirangerover/chatcord:1.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
