---
# Source: chatcord-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: chatcord-chatcord-chart
  labels:
    helm.sh/chart: chatcord-chart-0.1.0
    app.kubernetes.io/name: chatcord-chart
    app.kubernetes.io/instance: chatcord
    app.kubernetes.io/version: "1.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: chatcord-chart
    app.kubernetes.io/instance: chatcord
